package entities;
// Generated Jul 12, 2016 12:05:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comentarii generated by hbm2java
 */
@Entity
@Table(name = "comentarii", catalog = "test")
public class Comentarii implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idComentarii;
	private int idUserComentarii;
	private String textComentarii;
	private int idTaskComentarii;
	private String dateComentarii;

	public Comentarii() {
	}

	public Comentarii(int idUserComentarii, String textComentarii, int idTaskComentarii, String dateComentarii) {
		this.idUserComentarii = idUserComentarii;
		this.textComentarii = textComentarii;
		this.idTaskComentarii = idTaskComentarii;
		this.dateComentarii = dateComentarii;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_comentarii", unique = true, nullable = false)
	public Integer getIdComentarii() {
		return this.idComentarii;
	}

	public void setIdComentarii(Integer idComentarii) {
		this.idComentarii = idComentarii;
	}

	@Column(name = "id_user_comentarii", nullable = false)
	public int getIdUserComentarii() {
		return this.idUserComentarii;
	}

	public void setIdUserComentarii(int idUserComentarii) {
		this.idUserComentarii = idUserComentarii;
	}

	@Column(name = "text_comentarii", nullable = false, length = 500)
	public String getTextComentarii() {
		return this.textComentarii;
	}

	public void setTextComentarii(String textComentarii) {
		this.textComentarii = textComentarii;
	}

	@Column(name = "id_task_comentarii", nullable = false)
	public int getIdTaskComentarii() {
		return this.idTaskComentarii;
	}

	public void setIdTaskComentarii(int idTaskComentarii) {
		this.idTaskComentarii = idTaskComentarii;
	}

	@Column(name = "dateComentarii", nullable = false, length = 100)
	public String getDateComentarii() {
		return this.dateComentarii;
	}

	public void setDateComentarii(String dateComentarii) {
		this.dateComentarii = dateComentarii;
	}

}
