package entities;
// Generated Jul 12, 2016 12:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proiecte generated by hbm2java
 */
@Entity
@Table(name = "proiecte", catalog = "test")
public class Proiecte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProiect;
	private String projectName;
	private String projectDescription;
	private Date dateCreated;

	public Proiecte() {
	}

	public Proiecte(String projectName, String projectDescription, Date dateCreated) {
		this.projectName = projectName;
		this.projectDescription = projectDescription;
		this.dateCreated = dateCreated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_proiect", unique = true, nullable = false)
	public Integer getIdProiect() {
		return this.idProiect;
	}

	public void setIdProiect(Integer idProiect) {
		this.idProiect = idProiect;
	}

	@Column(name = "projectName", nullable = false, length = 50)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "projectDescription", nullable = false, length = 300)
	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
