package entities;
// Generated Jul 12, 2016 12:05:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Release generated by hbm2java
 */
@Entity
@Table(name = "release", catalog = "test")
public class Release implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRelease;
	private int idTaskRelease;
	private int idProiectRelease;
	private Date dateRelease;
	private String versiune;

	public Release() {
	}

	public Release(int idTaskRelease, int idProiectRelease, Date dateRelease, String versiune) {
		this.idTaskRelease = idTaskRelease;
		this.idProiectRelease = idProiectRelease;
		this.dateRelease = dateRelease;
		this.versiune = versiune;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_release", unique = true, nullable = false)
	public Integer getIdRelease() {
		return this.idRelease;
	}

	public void setIdRelease(Integer idRelease) {
		this.idRelease = idRelease;
	}

	@Column(name = "id_task_release", nullable = false)
	public int getIdTaskRelease() {
		return this.idTaskRelease;
	}

	public void setIdTaskRelease(int idTaskRelease) {
		this.idTaskRelease = idTaskRelease;
	}

	@Column(name = "id_proiect_release", nullable = false)
	public int getIdProiectRelease() {
		return this.idProiectRelease;
	}

	public void setIdProiectRelease(int idProiectRelease) {
		this.idProiectRelease = idProiectRelease;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateRelease", nullable = false, length = 10)
	public Date getDateRelease() {
		return this.dateRelease;
	}

	public void setDateRelease(Date dateRelease) {
		this.dateRelease = dateRelease;
	}

	@Column(name = "versiune", nullable = false, length = 100)
	public String getVersiune() {
		return this.versiune;
	}

	public void setVersiune(String versiune) {
		this.versiune = versiune;
	}

}
