package entities;
// Generated Jul 12, 2016 12:05:47 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "test")
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idStatus;
	private String textStatus;

	public Status() {
	}

	public Status(String textStatus) {
		this.textStatus = textStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_status", unique = true, nullable = false)
	public Integer getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(Integer idStatus) {
		this.idStatus = idStatus;
	}

	@Column(name = "text_status", nullable = false, length = 500)
	public String getTextStatus() {
		return this.textStatus;
	}

	public void setTextStatus(String textStatus) {
		this.textStatus = textStatus;
	}

}
